version: '3.7'

services:
  zentao:
    image: jefferlau/zentao:without-db
    build: .
    restart: always
    container_name: zentao
    ports:
      - "80:80"
    volumes:
      - ~/docker/zentao/www:/app/zentaopms
